import os

import yaml


DEFAULT_CONFIG = {
    "ui": {
        "title": "板金画像比較分析ツール（連係カメラ対応）",
        "description": "iPhoneを連係カメラとして接続し、撮影→比較を行います。",
    },
    "camera": {
        "device_index": 0,
        "capture_width": 0,
        "capture_height": 0,
        "live_refresh_ms": 200,
        "live_rotate_deg": 90,
        "quality_check": False,
        "quality_auto_retry": 3,
        "quality_retry_delay_ms": 300,
        "quality_white_ratio": 0.05,
        "quality_blur_threshold": 100,
    },
    "guide": {
        "enabled": True,
        "master_dir": "master",
        "master_image": "master_guide.png",
        "rotate_deg": 0,
        "scale": 0.7,
        "alpha": 0.35,
    },
    "analysis": {
        "preprocess_mode": "luminance",
        "preprocess_blur_ksize": 3,
        "preprocess_edge_method": "canny",
        "preprocess_edge_low": 50,
        "preprocess_edge_high": 150,
        "preprocess_blackhat_kernel": 15,
        "preprocess_contrast_gamma": 1.2,
        "quality_gate_enabled": False,
        "quality_gate_block": False,
        "quality_gate_white_ratio": 0.05,
        "quality_gate_blur_threshold": 100,
        "quality_gate_high_brightness": 250,
        "quality_gate_dark_ratio": None,
        "quality_gate_low_brightness": 5,
        "quality_gate_low_contrast": None,
        "quality_gate_specular_ratio": None,
        "quality_gate_specular_high_v": 240,
        "quality_gate_specular_low_s": 40,
        "auto_morph_kernel": True,
        "morph_kernel_coefficient_small": 60,
        "morph_kernel_coefficient_medium": 65,
        "morph_kernel_coefficient_large": 95,
        "detect_bbox": True,
        "foreground_mask": False,
        "foreground_mask_dilate_iter": 0,
        "foreground_mask_kernel": 15,
        "foreground_mask_keep_ratio": 0.0,
        "foreground_xor_add": False,
        "fg_edge_exclude_enabled": False,
        "fg_edge_exclude_iter": 2,
        "fg_edge_overlap_exclude_enabled": False,
        "fg_edge_raise_thresh_enabled": False,
        "fg_edge_raise_thresh_offset": 6,
        "background_overlap_check": False,
        "background_overlap_max_ratio": 0.5,
        "background_overlap_use_diff": False,
        "roi_enabled": False,
        "flip_compare": False,
        "flip_compare_min_ssim": 0.30,
        "flip_compare_min_improvement": 0.05,
        "auto_min_area": True,
        "min_area_ratio": 0.0001,
        "auto_diff_thresh": True,
        "diff_thresh_method": "hybrid",
        "diff_thresh_percentile": 95,
        "diff_thresh_contrast_low": 8,
        "diff_thresh_contrast_mid": 16,
        "diff_thresh_contrast_high": 24,
        "diff_thresh_min": 5,
        "diff_thresh_max": 50,
        "bbox_edge_ignore_ratio": 0.0,
        "bbox_min_area_relax_ratio": 0.0,
        "bbox_close_iter": 4,
        "bbox_open_iter": 1,
        "bbox_connectivity": 8,
        "bbox_edge_min_fill_ratio": 0.0,
        "bbox_edge_cut_enabled": False,
        "bbox_edge_cut_kernel": 3,
        "bbox_edge_cut_iter": 1,
        "bbox_drop_band_fill_ratio": None,
        "bbox_drop_band_width_ratio": None,
        "bbox_drop_band_height_ratio": None,
        "bbox_edge_roi_enabled": False,
        "bbox_edge_roi_canny_low": 50,
        "bbox_edge_roi_canny_high": 150,
        "bbox_edge_roi_kernel": 5,
        "bbox_edge_roi_close_iter": 2,
        "bbox_edge_roi_dilate_iter": 1,
        "bbox_edge_roi_min_area_ratio": 0.1,
        "bbox_edge_roi_max_area_ratio": 0.95,
        "bbox_edge_roi_require_closed": True,
        "bbox_edge_roi_border_margin": 2,
        "bbox_inner_erode_iter": 0,
        "bbox_inner_overlap_ratio": None,
        "bbox_rescue_drop_band_fill_ratio": None,
        "bbox_rescue_drop_band_width_ratio": None,
        "bbox_rescue_drop_band_height_ratio": None,
        "bbox_rescue_thresh_offset": 0,
        "bbox_rescue_morph_kernel": None,
        "bbox_rescue_close_iter": None,
        "bbox_rescue_open_iter": None,
        "bbox_rescue_edge_erode_iter": 1,
        "bbox_rescue_use_fg_edge_band": False,
        "bbox_rescue_min_area_ratio": None,
        "edge_sep_enabled": True,
        "edge_sep_min_dist": 3,
        "edge_sep_max_dist": 30,
        "edge_sep_step": 1,
        "hole_mask_enabled": False,
        "hole_mask_source": "edge_roi_or_foreground",
        "hole_mask_apply_mode": "master",
        "hole_mask_method": "auto",
        "hole_bg_border_ratio": 0.05,
        "hole_bg_dist_percentile": 95.0,
        "hole_bg_dist_scale": 1.5,
        "hole_bg_dist_min": 6.0,
        "hole_bg_dist_max": 60.0,
        "hole_inner_erode_iter": 1,
        "hole_expand_iter": 0,
        "hole_edge_exclude_enabled": False,
        "hole_edge_exclude_iter": 2,
        "hole_bbox_filter_enabled": False,
        "hole_bbox_filter_dilate_iter": 0,
        "hole_bbox_filter_overlap_ratio": 0.2,
        "hole_bbox_filter_max_area_ratio": 0.01,
        "hole_bbox_filter_use_center": True,
        "hole_min_area_ratio": 0.0002,
        "hole_max_area_ratio": 0.08,
        "hole_min_fill_ratio": 0.5,
        "hole_aspect_min": 0.6,
        "hole_aspect_max": 1.4,
        "hole_shrink_iter": 1,
        "hole_max_total_ratio": 0.15,
        "strong_bbox_enabled": False,
        "strong_bbox_percentile": 99.5,
        "strong_bbox_offset": 10,
        "strong_bbox_min_area_ratio": 0.3,
        "strong_bbox_min_area": 0,
        "strong_bbox_morph_kernel": 5,
        "strong_bbox_close_iter": 1,
        "strong_bbox_open_iter": 0,
        "strong_bbox_max_boxes": 5,
        "strong_bbox_use_edge_filter": True,
        "strong_bbox_edge_roi_enabled": False,
        "strong_bbox_edge_roi_canny_low": 50,
        "strong_bbox_edge_roi_canny_high": 150,
        "strong_bbox_edge_roi_kernel": 5,
        "strong_bbox_edge_roi_close_iter": 2,
        "strong_bbox_edge_roi_dilate_iter": 1,
        "strong_bbox_edge_roi_min_area_ratio": 0.1,
        "strong_bbox_edge_roi_max_area_ratio": 0.95,
        "strong_bbox_edge_roi_require_closed": True,
        "strong_bbox_edge_roi_border_margin": 2,
        "strong_bbox_drop_band_fill_ratio": 0.5,
        "strong_bbox_drop_band_width_ratio": 0.95,
        "strong_bbox_drop_band_height_ratio": 0.12,
        "crop_to_master_fov": False,
        "crop_compare_mode": True,
        "crop_two_pass": True,
        "crop_scale_min": 0.3,
        "crop_scale_step": 0.05,
        "crop_two_pass_min_matches": 10,
        "crop_ssim_degradation_threshold": -0.02,
        "crop_ssim_min": 0.3,
        "crop_ssim_min_skip_matches": 20,
        "crop_adopt_min_matches": 4,
        "crop_match_ratio_min": 1.0,
        "crop_mse_degradation_threshold": 0.05,
        "crop_try_rotations": False,
        "crop_rotation_search_step_deg": 10,
        "crop_master_padding_ratio": 0,
        "debug_crop_log": True,
        "debug_crop_log_path": "crop_debug.log",
        "debug_crop_save_images": False,
        "debug_crop_save_images_dir": "crop_debug_images",
        "debug_save_pipeline_stages": False,
        "debug_save_pipeline_dir": "debug_pipeline",
        "auto_align": True,
        "align_mode": "feature_points",
        "align_method": "orb",
        "align_edge_canny_low": 50,
        "align_edge_canny_high": 150,
        "align_max_features": 500,
        "align_match_ratio": 0.75,
        "align_compare_mode": True,
        "align_rematch_check": True,
        "align_fallback_mode": None,
        "align_fallback_on_reject": True,
        "align_match_improvement_threshold": 0.20,
        "align_inlier_improvement_threshold": 0.10,
        "align_ssim_improvement_threshold": 0.03,
        "align_ssim_degradation_threshold": -0.02,
        "align_mse_improvement_threshold": 0.10,
        "align_mse_degradation_threshold": -0.10,
        "align_min_rotation": 3.0,
        "align_min_translation": 30,
        "diff_thresh": 12,
        "min_area": 300,
        "morph_kernel": 20,
        "max_boxes": 6,
    },
    "output": {
        "base_dir": "outputs",
    },
}


def _deep_update(base, updates):
    for key, value in updates.items():
        if isinstance(value, dict) and isinstance(base.get(key), dict):
            _deep_update(base[key], value)
        else:
            base[key] = value
    return base


def load_config(config_path="config.yaml"):
    config = DEFAULT_CONFIG.copy()
    if not os.path.exists(config_path):
        return config
    with open(config_path, "r", encoding="utf-8") as f:
        loaded = yaml.safe_load(f) or {}
    return _deep_update(config, loaded)


def save_config_key(key: str, value, config_path: str = "config.yaml") -> None:
    """config.yaml の特定キーだけを更新して保存する（他のキーは保持）"""
    if os.path.exists(config_path):
        with open(config_path, "r", encoding="utf-8") as f:
            current = yaml.safe_load(f) or {}
    else:
        current = {}
    current[key] = value
    with open(config_path, "w", encoding="utf-8") as f:
        yaml.dump(current, f, allow_unicode=True, default_flow_style=False, sort_keys=False)
